name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install -g eslint
    - name: Run ESLint
      run: eslint -c .eslintrc.json ./src